---
- name: Change user password
  hosts: all
  become: yes
  tasks:
    - name: Update Basma's password
      user:
        name: basma
        password: "{{ 'basmapassword
        ' | password_hash('sha512') }}"