---
- name: Write and read a file using handler
  hosts: dev
  become: yes
  tasks:
    - name: Write to /etc/notes
      copy:
        content: "iam Mahmoud abdedayem"
        dest: /etc/notes
        mode: "0644"
      notify: Print file contents  # Triggers the handler

  handlers:
    - name: Print file contents
      command: cat /etc/notes
      register: file_content

    - name: Show the file content
      debug:
        msg: "{{ file_content.stdout }}"
