---
- name: Change user password
  hosts: all
  become: yes
  vars_files:
    - secrets.yaml
  tasks:
    - name: Print message
      ansible.builtin.debug:
        msg: "Hello, {{ new_password }}!"
    - name: Update Basma's password
      user:
        name: basma
        password: "{{ new_password | password_hash('sha512') }}"