---
- name: Create user Basma and set sudo permissions
  hosts: all
  become: yes
  tasks:
    - name: Create the dev group (if it doesn't exist)
      group:
        name: dev
        state: present

    - name: Create user Basma and add to the dev group
      user:
        name: basma
        groups: dev
        append: yes
        shell: /bin/bash

    - name: Grant sudo privileges to Basma
      copy:
        content: "basma ALL=(ALL) NOPASSWD: ALL"
        dest: /etc/sudoers.d/basma
        mode: "0440"